# Define a key for your exclusion rule (you can name it whatever you want, e.g., 'e1')
sonar.issue.ignore.multicriteria=e1

# Specify the Rule Key pattern to ignore
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:xml:S125

# Specify the file path pattern (use **/* for all files)
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*

